### ISSUE TITLE
Favicon designen & online zetten

### ISSUE THREAD

**Issue by Timendus** [verwijsafspraken/verwijsafspraken#10]

**Comment by hieu-onefold** [comment]
![favicon](https://user-images.githubusercontent.com/25198025/176651315-f19f4d45-2f4e-4869-83d6-ff00833c1b05.png)
![favicon](https://user-images.githubusercontent.com/25198025/176651317-af9d1f16-878e-45ec-9da0-731c3b7a630c.svg)
